name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        npm-version: [9.0]

    steps:
    - name: Run tests
      run: |
        cd nest-nest-hello-world
        npm run start
